version: '2'

services: 
    application:
        container_name: demo_app
        image: debian
        volumes:
            - ./:/var/www/laravel
    workspace:
        container_name: demo_workspace
        image: framgia/laravel-workspace
        volumes_from:
            - application
        tty: true
    php-fpm: 
        container_name: demo_php-fpm
        image: framgia/laravel-php-fpm
        volumes_from: 
            - application
        expose: 
            - '9000'
        links:
            - workspace
    nginx: 
        container_name: demo_nginx
        image: framgia/laravel-nginx
        ports: 
            - '3333:80'
        links: 
            - php-fpm
    mysql: 
        container_name: demo_mysql
        image: mysql:5.7
        expose: 
            - '3306'
        environment: 
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        container_name: demo_phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8888:80"
        links:
            - "mysql:mysql"